test:
  _target_: src.datasets.vctk_dataset.VCTKDataset
  dataset_split_file: "/content/Course_work_2/data/vctk_split_test.txt"
  vctk_wavs_dir: "/content/Course_work_2/data/VCTK/wavs"
  segment_size: 32768
  sampling_rate: 16000
  split: False
  instance_transforms: ${transforms.instance_transforms.inference}