test:
  _target_: src.datasets.vctk_dataset.VCTKDataset
  dataset_split_file: "/content/Course_work_2/data/vctk_test.txt"
  vctk_wavs_dir: "/content/Course_work_2/data/VCTK/wavs"
  segment_size: 8192
  sampling_rate: 16000
  split: True
  instance_transforms: ${transforms.instance_transforms.inference}