train:
  _target_: src.datasets.voicebank_dataset
  part: "train-clean-100"
  instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.voicebank_dataset
  part: "dev-clean"
  instance_transforms: ${transforms.instance_transforms.inference}
test:
  _target_: src.datasets.voicebank_dataset
  part: "test-clean"
  instance_transforms: ${transforms.instance_transforms.inference}
