defaults:
  - model: hifiplusplus
  - metrics: vctk_dataset
  - datasets: vctk_dataset
  - dataloader: example
  - transforms: example_only_instance
  - _self_
inferencer:
  device_tensors: ["audio"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "example" # any name here, can be a dataset name
  seed: 1
  from_pretrained: "/content/Course_work_2/data/VCTK/bwe1.pth" # path to the pretrained model